package com.naveench.portfolioassist.dto;

import java.util.List;
import java.util.Map;

/**
 * resultType tells the front end which visual layout to use (timeline,
 * project card, fit card, plain text, ...); card carries the structured data
 * for that layout, derived deterministically from the same content the
 * tools used - never re-generated by the model.
 */
public record AskResponse(
        String answer,
        String resultType,
        Map<String, Object> card,
        List<ToolCallView> toolCalls,
        long latencyMs
) {
}
